version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./database.csv:/usr/src/app/database.csv
      - ./config.env:/usr/src/app/config.env
      - ./email.html:/usr/src/app/email.html
